### ISSUE TITLE
Corrupt textures in Ancient Aliens v1.2

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#588]
This is **not** a new bug related to recent rendering changes, it's been around since at least the last release and probably much longer than that.

https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/aaliens
Various levels have corrupt textures here and there, starting around MAP09, but this is most prominently on display at the beginning of MAP24.  I've attached video clips to demonstrate what I'm referring to.

Interestingly, this seems to be something that was _introduced_ in later versions of this PWAD--I've also got a copy of 1.0, and it does not show these issues.

Video clip of the issue.  Warning--flashing lights.
https://github.com/user-attachments/assets/3232beda-d365-4bd9-b4d4-c88b86a774f1

For comparison, here is how DSDA Doom shows it.
https://github.com/user-attachments/assets/9854ab2e-a48b-408b-8ba7-8a3d1f16e067

**Comment by nstlaurent** [comment]
This was an interesting problem. It happens with the animated range with KS_FLSG1 - KS_FLSG6. The KS_FLSG6 is duplicated in the texture lump and near the end. This messes up the animations to animate through nearly 60 textures instead of the intended 6. Looked into Boom and it implemented hash lookups for textures but duplicates wouldn't overwrite, so I updated Helion to match this behavior.

**Comment by lemming104** [comment]
Confirmed that 100a895d14c778eb6760b97c6fb47e0922cc4984 fixes this problem.  I also checked a couple other maps in that WAD that previously showed similar texture glitches, and those also appear to be fixed (I didn't explicitly list them when I opened this issue because I figured they were all an equivalence class, and the beginning of MAP24 is both the most accessible and most obvious instance).

Thanks!
