### ISSUE TITLE
Update documentation (and UX?) for texture filtering settings to mention palette color mode behaviors

### ISSUE THREAD

**Issue by lemming104** [Helion-Engine/Helion#589]
With the addition of the true-color/palette color mode selection, there are a handful of graphics settings that only seem to do anything when in true-color mode, and have no effect in palette mode.  Most of these pertain to texture filtering, which seems reasonable enough (I can't imagine why someone would select a retro palette _and_ a blurry texture filter).  However, the documentation for these settings should probably either be updated to reflect what works in which mode, or maybe settings that have no impact should be locked-out when in palette mode (although that's obviously more work).

For example, it seems like palette mode renders using nearest-neighbor texture filtering (see screenshots) regardless of settings.  I don't really see a difference between 1x and 16x anisotropic filtering when in palette mode either, but based on the way the texture filtering options don't do anything, maybe it's not even generating MIP maps and such to begin with?

Unrelated:  What do the texture transparency settings actually _do_?  :)

Here is a screenshot with nearest-neighbor filtering selected, in the palette graphics mode:
![helion_20240806_08 16 46 7401](https://github.com/user-attachments/assets/c9428c27-d782-41c3-ae74-2b71928370b1)

The same, but with trilinear selected:
![helion_20240806_08 16 54 0978](https://github.com/user-attachments/assets/4ee6f2d0-c95d-45d4-b551-33ca1b04a85a)

True-color + trilinear, showing that the filter options still do something:
![helion_20240806_08 17 37 3565](https://github.com/user-attachments/assets/85d3f91d-16e5-451d-b904-4d497dceff91)

**Comment by nstlaurent** [comment]
The options should probably be disabled when using palette rendering. Texture filtering and anisotropic filtering can't work for palette rendering because they modify the RGBA values of the color, so either one makes it necessary to use true color. The way the palette rendering works is the index of pixel from doom's image format is written to the R component of the RGBA image. The shader uses this value to look it up through colormap and palette so any filtering would modify/interpolate the R value would result in an incorrect lookup.

I think the video resolution is locked out when fullscreen is selected, so it might not be that difficult, but I don't exactly remember.

The texture transparency would disable alpha for lines, which really only exists with the Boom translucent line type.

**Comment by lemming104** [comment]
Yeah, it makes intuitive sense that filtering, which usually does _some kind_ of interpolation, wouldn't work correctly in a paletted color mode, and would _at best_ produce weirdly posterized results.  I didn't realize that all of the colormap stuff goes through a single component color, interesting.  :)

**Comment by nstlaurent** [comment]
Disabled texture filter options if palette mode is selected.

**Comment by lemming104** [comment]
Confirmed that this is fixed by 04829e526ac083036d957441554ca16bb47bad40.  These options are greyed out and nonfunctional when in palette mode, active when in true-color mode.
