### ISSUE TITLE
Screen transition effects?

### ISSUE THREAD

**Issue by NastyFlytrap** [Helion-Engine/Helion#599]
I miss the melting on death, but i would like to see all of them back, honestly. Shouldnt be too hard to implement

**Comment by 72hr** [comment]
I wrote a shader using decino's video on it as reference. I need to figure out how to actually set it up properly in the engine (it's in `FramebufferRenderer` here which is why the HUD is rendering on top), but it should be usable if I can get to that point.

https://github.com/user-attachments/assets/25cb8ad5-eef9-4493-a87d-35d20a2e0f2a

https://github.com/72hr/Helion/tree/melt-wip

**Comment by NastyFlytrap** [comment]
Thanks! Any chance of re-creating the other screen effects that GZDoom has too? Its one of those small little neat features i quite like about that port.

**Comment by nstlaurent** [comment]
@72hr what you can do is a make a second program in the frame buffer renderer and call it m_screenMeltProgram and have m_program be what it was before. You will have to make sure that it is setting the alpha to 0 for the black pixels so the world can be shown from behind it. Add a second call for RenderScreenMelt() to use and render using your screen melt program and then you can do this in DrawFrameBufferOnDefault()

    private void DrawFramebufferOnDefault()
    {
        m_framebufferRenderer.Framebuffer.Unbind();
        m_framebufferRenderer.Render();
        m_framebufferRenderer.RenderScreenMelt();
    }
    
    Once that is working it we can add a DrawScreenMelt RenderCommand in so that the renderer will know whether to call just m_framebufferRenderer.Render vs  m_framebufferRenderer.Render and RenderScreenMelt
    
Edit: Just realized Doom also did to this HUD. I will have to think about that part a bit.

**Comment by nstlaurent** [comment]
I think we will need what I described above either way. We will likely need a second framebuffer that that is the screen resolution that everything renders to. So instead of the virtual framebuffer rendering to default, we would have to GL.BlitFramebuffer to render it to the main framebuffer that is the screens resolution and draw everything to that. Then render this framebuffer to the default.

**Comment by 72hr** [comment]
Made some progress:

https://github.com/user-attachments/assets/cbc803e4-d6b7-4379-a214-cac111710ed2

Not sure about the config location and code structure though. Also need to tweak how it's started because progress is never 0 in `HandleTransitionCommand()` if you specify a map on the command line, so it won't fire there.

https://github.com/Helion-Engine/Helion/compare/dev...72hr:melt-wip

**Comment by lemming104** [comment]
I've always loved the "melt" wipe, so it's good to see it in Helion.  :)

**Comment by 72hr** [comment]
I spent some time trying to figure out why it was flickering on startup and after intermissions, and I ended up structuring it so the framebuffer always exists rather than created during the first transition frame, and then the framebuffer copy happens at the beginning of a render before the other commands.

Having the copy come first is critical so it's not serving up the current partial frame, but I also wondered if it really makes sense to have a list of TransitionCommands since there's only gonna be one at a time. Would it make sense to set a single one on the RenderCommands class, then the input ordering is irrelevant? At the top of Render() where I copy, I could just check if a non-null command requests a copy, and then at the bottom I can check again and apply the effect before rendering the main framebuffer to default.

Comparison:
https://github.com/72hr/Helion/compare/melt-wip...melt-wip-2

**Comment by nstlaurent** [comment]
Yeah I think it's fine to have one. One thing I wanted to do for the transitions was have the loading layer just basically be the bottom text bar and render whatever was there last instead of always putting the titlepic on the screen. At the time I didn't want to setup all the buffers/commands etc but this is pretty much there. It would be cool to match the doom behavior where it uses the last frame to fade/melt into the next transition.

**Comment by nstlaurent** [comment]
@72hr if you have discord we have a server:
https://discord.gg/NHRGFcca

**Comment by NastyFlytrap** [comment]
> I've always loved the "melt" wipe, so it's good to see it in Helion. :)

Yea, me too! It feels very 90's, close to my heart!



> I spent some time trying to figure out why it was flickering on startup and after intermissions, and I ended up structuring it so the framebuffer always exists rather than created during the first transition frame, and then the framebuffer copy happens at the beginning of a render before the other commands.
> 
> Having the copy come first is critical so it's not serving up the current partial frame, but I also wondered if it really makes sense to have a list of TransitionCommands since there's only gonna be one at a time. Would it make sense to set a single one on the RenderCommands class, then the input ordering is irrelevant? At the top of Render() where I copy, I could just check if a non-null command requests a copy, and then at the bottom I can check again and apply the effect before rendering the main framebuffer to default.
> 
> Comparison: [72hr/Helion@melt-wip...melt-wip-2](https://github.com/72hr/Helion/compare/melt-wip...melt-wip-2)

Also, Decino made an excellent video about this, you should watch it to make sure its the authentic screen wipe, thats true to the original, even if the code running it is not the same

https://www.youtube.com/watch?v=lUsCXSNhHmI

**Comment by lemming104** [comment]
Melt wipes added in https://github.com/Helion-Engine/Helion/pull/665
