### ISSUE TITLE
Cannot build helion on debian stable

### ISSUE THREAD

**Issue by khades** [Helion-Engine/Helion#604]
Debian stable, dotnet8

console output 

```
khades@abberation:~/Helion$ LANG=C ./Scripts/build.sh 
  Determining projects to restore...
  All projects are up-to-date for restore.
  Core -> /home/khades/Helion/Core/bin/Release/net8.0/Core.dll
  Tests -> /home/khades/Helion/Tests/bin/Release/net8.0/Tests.dll
  Client -> /home/khades/Helion/Client/bin/Release/net8.0/Helion.dll
/home/khades/Helion/Client/Client.csproj(64,5): error MSB3941: Failed to zip directory "/home/khades/Helion/Client/Assets/Assets" because it does not exist or is inaccessible.

Build FAILED.

/home/khades/Helion/Client/Client.csproj(64,5): error MSB3941: Failed to zip directory "/home/khades/Helion/Client/Assets/Assets" because it does not exist or is inaccessible.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.21
khades@abberation:~/Helion$ 
```

This "assets" doubling is weird.

**Comment by nstlaurent** [comment]
Oh that script was probably never updated after the building procedures changed. From the Client folder I run this command to build for linux:
dotnet publish -c Release -r linux-x64 --self-contained=true -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true

This should build it to:
Client\bin\Release\net8.0\linux-x64\publish

**Comment by lemming104** [comment]
That's actually integral to the .csproj file now; it's using the MSBuild "zip" task ever since I changed the build stuff.

Assets/Assets is just how it's been; it's actually the correct path:  https://github.com/Helion-Engine/Helion/tree/dev/Assets/Assets.  If nstlaurent wants to move it, we can update the .csproj files accordingly; I just didn't want to be responsible for a PR that looks like it's hitting hundreds of files.  😆 

It's much _more_ interesting that it's trying to find that under Client, which is not correct.  

I might need to revisit how it generates that path.  It _should_ use the root of the repo as the beginning of the path because of the variable I stuck in there, but maybe that's not resolving for some reason.

**Comment by lemming104** [comment]
What happens if you rename `Directory.Build.Targets` in the root dir to `Directory.Build.targets`?  I forget whether MSBuild uses case-sensitive file names there on *NIX OSes.

**Comment by lemming104** [comment]
I just confirmed, on a WSL2 Ubuntu install, that this is indeed the issue.  It's only noticeable if the mounted filesystem is case-sensitive (so, not a mounted directory from your Windows file system).

At least that is an easy fix.

**Comment by lemming104** [comment]
Just to explain what is going on here:  If you go to the line it mentions in the .csproj file, you'll see that it begins with `$(HelionRootDir)`.  In MSBuild, `$(someName)` denotes a named property (variable).  You can define these anywhere; and they're really useful for doing stuff like constructing path strings on the fly.

You'll notice that the `$(HelionRootDir)` string is not actually defined in that project.  That's because MSBuild has an interesting (and intentional) behavior where it crawls backwards up the directory structure until it finds files named `Directory.Build.props` and `Directory.Build.targets`, and it basically executes the stuff in there first.  The difference between the two is that `Directory.Build.props` is basically static, whereas `Directory.Build.targets` can contain things that are evaluated at build time.   This is actually a _really_ useful behavior for adding stuff that you can consume in projects in child directories.

In Directory.Build.props, I did some stuff like apply common version IDs and build settings to every project in the directories below.  In Directory.Build.targets, I actually set the HelionRootDir property to _whatever directory the .targets file was found in_.
```
<HelionRootDir>$(MSBuildThisFileDirectory)</HelionRootDir>
```

The issue is that, since I screwed up the capitalization, *NIX-like OSes don't load that Targets file, and the value of `$(HelionRootDir)`, under those circumstances, is the same as any other undefined property in MSBuild: an empty string.

Thank you for attending my TED talk.  😆

**Comment by lemming104** [comment]
My fix was just merged.  @khades , can you try again and let us know if that solved it for you?

**Comment by khades** [comment]
@lemming104 yepp, builds rn
