### ISSUE TITLE
high CPU usage from NAudioMusicPlayer

### ISSUE THREAD

**Issue by 72hr** [Helion-Engine/Helion#625]
I noticed whenever I started up Ancient Aliens MAP01 my CPU fans would start spinning up, and then it would go away once the beach ambience was replaced by the MIDI.

This loop is using a lot of CPU:

https://github.com/Helion-Engine/Helion/blob/506825dafde9de7b613e18a99f4aef9fa913aebf/Client/Music/NAudioMusicPlayer.cs#L64-L65

If I sleep the thread in between checks, or wait instead, then it seems to be OK. Is a `ManualResetEventSlim` appropriate here?

**Comment by lemming104** [comment]
I played around with that a bit, and that looped call to Play() seems completely unnecessary.  The issue is just that it needs _something_ to prevent it from hitting the end of that method, where it disposes the AudioStream.

It seems like we can simplify this a bit.

**Comment by lemming104** [comment]
This seems like one way to avoid that loop, and it seems to work on my machine.  Does it work OK for you, too?
https://github.com/Helion-Engine/Helion/pull/626

**Comment by 72hr** [comment]
It plays and loops correctly. `FluidSynthMusicPlayer` also waits for the music to end before returning, so their behaviors would differ. But `MusicPlayer` which wraps them both doesn't, so it may not matter. As far as I can tell everything gets cleaned up properly.

**Comment by lemming104** [comment]
@nstlaurent commented elsewhere that he will need make other changes in this whole MusicPlayer area, so I'd prefer to stay away from doing _too_ much in here until he's decided what to do.

The NAudio stuff is problematic as-is, because it only works on Windows.  We might also want to support some of the more popular tracker music formats at some point too, so there's sort of an open question about whether we should just get a wrapper for libsndfile, or make a wrapper for ZMusic from the GZDoom project.

**Comment by nstlaurent** [comment]
I think the change to NAudioMusicPlayer is good. I am updating MusicPlayer to handle loading in a thread not just playback. This has become more important since the id24 spec has music change lines and handling the music load in the game loop creates a noticeable stutter.
