### ISSUE TITLE
save menu can run out of slots

### ISSUE THREAD

**Issue by 72hr** [Helion-Engine/Helion#695]
With autosaves getting created it's possible to have way more than the 9 slots that show, and then you have to delete a bunch of them before there's a free slot.

**Comment by lemming104** [comment]
Seems that there are a few things that could/should be done here.
1.  Add either scrolling or pagination to the save/load menu
2.  Raise the number of slots.  I believe it's arbitrarily set to nine?  At least, that's what I seem to remember from looking at it earlier today.
3. Rotate autosaves rather than just flooding the directory with them
